# Generated by Django 4.2.11 on 2024-04-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_urunkategori_urunvitrin_urunler_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
