# Generated by Django 4.2.11 on 2024-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_urunler_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='baslik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
