# Generated by Django 4.2.11 on 2024-06-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_hizlilinkler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
