# Generated by Django 4.2.11 on 2024-06-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_menuitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='device',
            field=models.CharField(choices=[('mobil', 'Mobil'), ('masaüstü', 'Masaüstü')], default='masaüstü', max_length=15),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
