# Generated by Django 4.2.11 on 2024-06-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_sliders_device_alter_menuitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunvitrin',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
