# Generated by Django 4.2.11 on 2024-06-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_urunvitrin_slug'),
    ]

    operations = [
    ]
