# Generated by Django 4.2.11 on 2024-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunkategori',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
