# Generated by Django 4.2.11 on 2024-06-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_urunkategori_slug'),
    ]

    operations = [
    ]
