# Generated by Django 4.2.11 on 2024-06-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_populate_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urunvitrin',
            name='slug',
        ),
    ]
