# Generated by Django 4.2.11 on 2024-06-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_urunvitrin_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='vitrin_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.urunvitrin'),
        ),
    ]
