# Generated by Django 4.2.11 on 2024-06-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_urunvitrin_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
