# Generated by Django 4.2.11 on 2024-06-30 16:24

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_balikgorsel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaslikGorsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=myapp.models.kapakfoto_path_baslikgorsel)),
                ('durum', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='BalikGorsel',
        ),
    ]
